### ISSUE TITLE
Add support to release aarch64 wheels

### ISSUE THREAD

**Issue by odidev** [htcondor/htcondor_manylinux_docker#4]
On aarch64, ‘pip install htcondor’ gives the following error:

`ERROR: Could not find a version that satisfies the requirement htcondor (from versions: none)`
`ERROR: No matching distribution found for htcondor`

Please let me know your interest in releasing aarch64 wheels. I can help with this.

**Comment by odidev** [comment]
@timtheisen Could you please let me know your interest in releasing aarch64 wheels. It would be really helpful for aarch64 users.

**Comment by timtheisen** [comment]
I'll check with our developer group and report back here.

**Comment by odidev** [comment]
@timtheisen, did you get a chance to discuss with your developer group?

**Comment by odidev** [comment]
@timtheisen, did you get a chance to discuss with your developer group?

**Comment by timtheisen** [comment]
Fixed by PR #10 
This will be released with HTCondor 23.1.0 on October 31, 2023
